name: topics_advanced
description: A more advanced example of how to use Momento Topics and enable logging.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  momento: ^0.4.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
